### ISSUE TITLE
新建组织 URL跳转 安全问题

### ISSUE THREAD

**Issue by qingzhenduyu** [Yuanpei-Intelligence/YPPF#100]
现在的新建组织 在审核通知时，跳转的URL是显式的，如果有人修改URL中的ID，极易出现，处理了另外一条通知的问题
解决办法有两种：
（1）从通知入手，加入外键（在哪加），解决URL中加入ID的问题；
（2）对URL中的ID进行加密

**Comment by qingzhenduyu** [comment]
经费审批也是这样的问题

**Comment by YWolfeee** [comment]
难道审核的逻辑不是说访问一个页面一开始先看这个人有没有权利审核这个嘛？

**Comment by qingzhenduyu** [comment]
> 难道审核的逻辑不是说访问一个页面一开始先看这个人有没有权利审核这个嘛？

是滴，这个没问题，但是有可能出现有人恶意发送并且，修改ID的情况

**Comment by qingzhenduyu** [comment]
领取issue,预计工时2

**Comment by qingzhenduyu** [comment]
已解决

**Comment by panhongtao07** [comment]
没完全解决，不同审核间复制GET参数仍可以通过验证，我加入了各自的字符串以区别
