### ISSUE TITLE
人事变动没有文字提示

### ISSUE THREAD

**Issue by qingzhenduyu** [Yuanpei-Intelligence/YPPF#101]
![52d75adb93d05b9fa065012e2fc8286](https://user-images.githubusercontent.com/56719355/129666897-e240812e-38f5-43ec-8fa2-3d3396b131b8.png)
![11a5fa9f27812a0777cbbb22176a54d](https://user-images.githubusercontent.com/56719355/129666908-4c969d9c-4aed-4ff9-8074-02fa1d663a84.png)
如图，人事变动可以和通知信箱一样，做一个文字提示

**Comment by XuRuihan** [comment]
申请加入组织和组织审批是有提示的。你说的没有提示是怎么变动的

**Comment by YWolfeee** [comment]
他说的应该是上面这个提示。这个提示我觉得可以统一设计。麻烦 @sunyb-dot 和tmc着手操作一下，尽快给我一个每个页面的提示文档。

**Comment by XuRuihan** [comment]
现在这个文字提示不做了是吗，我看通知信箱的提示被注释掉了

**Comment by YWolfeee** [comment]
啊？你没有导入help

**Comment by YWolfeee** [comment]
/loadhelp/

**Comment by qingzhenduyu** [comment]
这个问题应该是解决掉了，我关了哈
