### ISSUE TITLE
通知信箱 点击URL 查看历史消息

### ISSUE THREAD

**Issue by qingzhenduyu** [Yuanpei-Intelligence/YPPF#102]
因为做审核、和一些消息的处理时，是跳转到另一个页面做的，但是通知处理过后，想要查看历史消息去点击URL时，如果该事项已被处理，则目前无法查看具体的历史信息。

**Comment by linhaowei1** [comment]
这个问题我觉得需要根据具体的对应功能修改，不同通知对于”具体的历史信息“的定义都比较模糊，我对除了转账以外其他类型的事务不是很了解，这个或许需要推迟或assign给别人？

**Comment by YWolfeee** [comment]
这个我来做吧 @panhongtao07 记得push我下，我太多事了x
