### ISSUE TITLE
第一次修改密码的头像加载不出来+初次修改密码没有二次确认

### ISSUE THREAD

**Issue by qingzhenduyu** [Yuanpei-Intelligence/YPPF#110]
![image](https://user-images.githubusercontent.com/56719355/129698983-1b63efbb-0d96-4300-a41d-c0bc10969647.png)
如图

**Comment by sunyb-dot** [comment]
还有一个问题，现在对于密码的强度好像没有要求啊

**Comment by YWolfeee** [comment]
你别的default头像能出来吗？这个我感觉我的能出来呀。
密码强度@panhongtao07

**Comment by sunyb-dot** [comment]
头像我这里已经是可以加载出来了的

**Comment by qingzhenduyu** [comment]
> 你别的default头像能出来吗？这个我感觉我的能出来呀。
> 密码强度@panhongtao07

嗯嗯，今天测试了一下，又可以了，可能是已经被同学默默改好了，当时我测试的时候确实没有头像加载

**Comment by panhongtao07** [comment]
目前没有增加密码强度的必要吧，感觉只是恶心人）
