### ISSUE TITLE
组织主页难找

### ISSUE THREAD

**Issue by qingzhenduyu** [Yuanpei-Intelligence/YPPF#114]
作为一个完全没有接触过组织主页和个人主页的人，我花了好久才意识到右上角的房子图案是组织（个人）主页的意思
建议在页面里显示地再加一个 组织（个人）主页 的入口

**Comment by panhongtao07** [comment]
个人主页也一样吧，不如一起骂）

**Comment by Sophie-zh** [comment]
这个改完了吧，应该可以close了

**Comment by qingzhenduyu** [comment]
组织主页还没像个人那样做一个明显的在左上角

**Comment by qingzhenduyu** [comment]
所以可能是不是再加一个？
