### ISSUE TITLE
通知删除可以考虑改成伪删除，status_change可以增加转化为指定状态的功能

### ISSUE THREAD

**Issue by panhongtao07** [Yuanpei-Intelligence/YPPF#130]
方便以后数据库统计。数据库添加一个状态为DELETED，和一个筛选有效通知的manager。
如果这么改，理清所有相关逻辑，比如页面呈现、status_change、所有调用了通知的地方，以及发送通知到微信（已删除的应该不能发送）。
status_change可以考虑接受一个可选参数，表示将要设置的状态，而不是现在默认的翻转状态。

**Comment by panhongtao07** [comment]
把之前那个分成俩任务了，做不做都ok

**Comment by YWolfeee** [comment]
这个不是lhw最新的已经搞定了吗？

**Comment by panhongtao07** [comment]
不是，现在的是数据库删除

**Comment by XuRuihan** [comment]
我们有什么字段是允许用户删除的吗，我感觉没有东西可以删啊

**Comment by YWolfeee** [comment]
@linhaowei1

**Comment by linhaowei1** [comment]
> @linhaowei1

现在确实是数据库删除，我之后改一下status_change这个API

**Comment by linhaowei1** [comment]
#143 已发pr143
