### ISSUE TITLE
做一个简单的反馈界面，直接向管理者发送通知

### ISSUE THREAD

**Issue by panhongtao07** [Yuanpei-Intelligence/YPPF#137]
要求：
1.管理者可能是人或列表，用学号/姓名标识（应该是学号，自行考虑），存储在json中
2.反馈内容暂时只要求纯文本，不要求存储在数据库中，即反馈内容只存在于通知中
3.通知可以是知晓类通知
进阶要求1.处理后向反馈者发送通知，表示该通知已读（可能需要修改数据库，联系lhw）
进阶要求2.a.反馈通知可以增加操作类型，包括[已处理]和[拒绝处理]，并向反馈者发送通知（可能需要修改数据库，联系lhw）
进阶要求2.b.完成反馈的对话界面，每次对话创建通知

**Comment by YWolfeee** [comment]
最后再做，现在别做。

**Comment by pkuGenuine** [comment]
可以关了吧，现在可以直接向智慧书院提反馈
