### ISSUE TITLE
转账确认通知没有文字说明

### ISSUE THREAD

**Issue by panhongtao07** [Yuanpei-Intelligence/YPPF#139]
![image](https://user-images.githubusercontent.com/59553164/130035096-25ced615-f855-4fb8-bce9-b5dfc9182747.png)
![image](https://user-images.githubusercontent.com/59553164/130035206-7da3d2cd-e14f-4e87-baf9-e16c1b0a1d7d.png)

**Comment by YWolfeee** [comment]
就补上这个转账的那个message就好
