### ISSUE TITLE
创建组织页，如果有组织之间重名，会失败

### ISSUE THREAD

**Issue by sunyb-dot** [Yuanpei-Intelligence/YPPF#141]
需要补充一下报错信息

**Comment by sunyb-dot** [comment]
尝试用两个账户新建一个命名为“xxx”的组织，第一个可以正常审核，第二个不行，应该是因为(1062, "Duplicate entry 'xxx' for key 'oname'")

**Comment by panhongtao07** [comment]
同时注意其他可能和组织&其他新建组织的冲突

**Comment by YWolfeee** [comment]
这个应该是，不允许创建一个重名组织。就是new组织的时候如果存在这个组织那么就提示不能创建，相当于是POST的一个warning（黄色）

**Comment by qingzhenduyu** [comment]
理论上是只报POST的一个warning的，我再仔细问一下
