### ISSUE TITLE
组织左边栏将二级菜单改成一级

### ISSUE THREAD

**Issue by YWolfeee** [Yuanpei-Intelligence/YPPF#146]
![image](https://user-images.githubusercontent.com/48834325/130158233-85feb455-3296-4343-9f98-f0e5f7b9e02b.png)
像这样：
![image](https://user-images.githubusercontent.com/48834325/130158251-52b6f124-e895-46c8-859c-f2eaa8b2d041.png)

图标可以在 [svg](https://feathericons.com/) 上找

**Comment by panhongtao07** [comment]
补充说明：这些svg是扒了半天找到的同风格svg，如果意义类似直接抄这几个就好了

**Comment by YWolfeee** [comment]
上面那个svg有链接

**Comment by Sophie-zh** [comment]
OK看到了
