### ISSUE TITLE
新建组织信息为空时有错误

### ISSUE THREAD

**Issue by YWolfeee** [Yuanpei-Intelligence/YPPF#147]
![image](https://user-images.githubusercontent.com/48834325/130185173-5dd938ab-c71c-4da4-9454-da8e1c777262.png)

如果什么信息都不填写，那么新建组织会有问题。
实际的逻辑应该是：如果什么都不填写，那么系统警告用户信息提醒不全面。

**Comment by qingzhenduyu** [comment]
该issue的解决已PR上去
今中午讨论的内容下午讨论完再PR
