### ISSUE TITLE
能否将Profile与地下室预约系统的登录状态同步呢？

### ISSUE THREAD

**Issue by ZyonZhang** [Yuanpei-Intelligence/YPPF#150]
每次进入Profile都需要登录，但从Profile进入地下室预约系统还需要登录一次输入一样的内容；更要命的是从预约系统回到Profile还需要再登录一次，使用体验相当一般。既然两边的登陆界面和账户都是统一的，那是不是也能将登录状态同步呢？这样就可以节省后两个登录的过程，使用起来会简洁很多。

**Comment by YWolfeee** [comment]
参见Issue 56，是同一个问题，已经解决，可以clsoe
