### ISSUE TITLE
新建组织会有bug

### ISSUE THREAD

**Issue by linhaowei1** [Yuanpei-Intelligence/YPPF#159]
![image](https://user-images.githubusercontent.com/56622542/130307300-de95967b-f47c-427c-8118-2626bd3d914d.png)
有几个问题：
1. 我在服务器上测试，默认的选项好像是学生小组，但是我申请之后会变成体育队。。。
2. 在我本地测试，即使创建成功（指数据库里出现了创建的条目）都会提示上面图片显示的创建失败

**Comment by linhaowei1** [comment]
哦，这里的创建失败指的是”通知“创建失败

**Comment by qingzhenduyu** [comment]
嗯，我本地测试一下
你本地是不是没有审核人员的信息呢
