### ISSUE TITLE
个人主页-我的组织总是呈现滚动条，而且很丑

### ISSUE THREAD

**Issue by panhongtao07** [Yuanpei-Intelligence/YPPF#167]
![1629609519(1)](https://user-images.githubusercontent.com/59553164/130343362-ab578ab6-e696-4691-88ae-eff237396faa.png)

**Comment by Sophie-zh** [comment]
感觉背景有点花了

**Comment by mrlazy1708** [comment]
组织卡片的美观程度和图片的选择有很大关系。请提出您认为的美观方案，谢谢

**Comment by panhongtao07** [comment]
我要求不高，能不能不要在这个位置显示滚动条，要么不显示要么放旁边，背景我暂时还可以接受
