### ISSUE TITLE
所有错误信息发送到admin的微信上

### ISSUE THREAD

**Issue by YWolfeee** [Yuanpei-Intelligence/YPPF#171]
像地下室那样。

**Comment by panhongtao07** [comment]
你想累死我）

**Comment by panhongtao07** [comment]
优先级不高，而且大部分错误信息本来就是页面处理的一部分，只有真正发生意外才应该发送错误信息，你这种设置不合理；我倾向于给所有view增加一个包装器，在调用异常失败时进行额外的发送

**Comment by panhongtao07** [comment]
优先级不高，而且大部分错误信息本来就是页面处理的一部分，只有真正发生意外才应该发送错误信息，你这种设置不合理；我倾向于给所有view增加一个包装器，在调用异常失败时进行额外的发送

**Comment by YWolfeee** [comment]
同意

**Comment by XuRuihan** [comment]
> 给所有view增加一个包装器，在调用异常失败时进行额外的发送

这样的话是不是把所有的代码都放在try里？这样会不会效率很低？

**Comment by YWolfeee** [comment]
> > 给所有view增加一个包装器，在调用异常失败时进行额外的发送
> 
> 这样的话是不是把所有的代码都放在try里？这样会不会效率很低？

我写完了 只需要把所有todo debug发过来 不需要全部try 只有很少的应该是"意料之外"
