### ISSUE TITLE
新建组织有一些bug

### ISSUE THREAD

**Issue by linhaowei1** [Yuanpei-Intelligence/YPPF#172]
1. 如果我新建了一个组织，又修改了申请信息，一共会发送两条notification（创建+修改）。主管老师通过创建的那条notification点进去，确认了之后，组织已新建，这条notification被设为已读，但另一条（修改）的notification会永远存在。
2. 老师点击确认后，该页面未刷新，按钮不会消失，需要手动刷新。

**Comment by YWolfeee** [comment]
应该是刷新先后顺序的问题 @qingzhenduyu  先处理POST，再准备前端呈现的变量

**Comment by qingzhenduyu** [comment]
另一条修改的notification因为目前的通知没有办法关联到申请组织的实例，所以，另一条通知是存在的，现在的办法是，再点击这个通知进入处理页面的时候，通知会被自动设置已读

**Comment by panhongtao07** [comment]
点击另一条通知进去的时候会设成已读吧，我觉得这就够了

**Comment by linhaowei1** [comment]
好的，那第1点没啥问题了~
