### ISSUE TITLE
功能界面字体不统一

### ISSUE THREAD

**Issue by Little-Stream** [Yuanpei-Intelligence/YPPF#183]
![image](https://user-images.githubusercontent.com/79560566/130658080-323029d0-ada9-4b82-92f1-bfae814134a1.png)
![image](https://user-images.githubusercontent.com/79560566/130658166-36f8cba5-ee6f-4c8e-850c-b60e618bcc6f.png)
 部分功能界面字体大小和形式不统一，是否需要更改？

**Comment by YWolfeee** [comment]
已经更改 稍后我拉到服务器
