### ISSUE TITLE
活动徽章显示颜色不统一

### ISSUE THREAD

**Issue by qingzhenduyu** [Yuanpei-Intelligence/YPPF#197]
![image](https://user-images.githubusercontent.com/56719355/131089505-8ce3427f-0ebd-49ec-87cf-714a627198d9.png)
![68303195c13872430f927e99bdd8cd3](https://user-images.githubusercontent.com/56719355/131089527-46d530c5-fa94-492b-9c39-527450b156a7.png)
如上图，都是已结束，但是颜色不统一

**Comment by Sophie-zh** [comment]
我这边最新版没问题啦，再试试看？

**Comment by qingzhenduyu** [comment]
> 我这边最新版没问题啦，再试试看？
对！我把这个issue关了哈
