### ISSUE TITLE
通知信箱界面，可以把这些卡片的高度设定为一个统一值吗

### ISSUE THREAD

**Issue by sunyb-dot** [Yuanpei-Intelligence/YPPF#208]
![image](https://user-images.githubusercontent.com/76576839/131279481-ccce3bec-ae7f-44e3-83af-ed1ca5b7faa0.png)
现在这些卡片有点参差，感觉统一了可能更好看一点

**Comment by YWolfeee** [comment]
但其实整体上是统一的，如果右边的长了下面的也会跟着一起长；如果强行统一可能要写js，时间关系先不管了吧
