### ISSUE TITLE
组织主页-呈现活动档案时有奇怪的bug

### ISSUE THREAD

**Issue by sunyb-dot** [Yuanpei-Intelligence/YPPF#215]
![image](https://user-images.githubusercontent.com/76576839/131381993-3e1a8acd-e858-4a6c-acd1-755687d55f7b.png)
感觉不应该出现这样的问题呀，很疑惑，而且不会改；在最新的pr里我把这段好好排了个版，感觉哪些if语句应该对上了

**Comment by sunyb-dot** [comment]
啊，因为162.105上还没有活动，这个是在本地跑的结果，不过应该是最新的develop分支

**Comment by XuRuihan** [comment]
应该是 `{% ...%}` 不能换行的原因
