### ISSUE TITLE
登录界面图片不会随网页大小变化而变化

### ISSUE THREAD

**Issue by Little-Stream** [Yuanpei-Intelligence/YPPF#228]
![image](https://user-images.githubusercontent.com/79560566/131649023-c593f660-c181-4c6d-8385-cb73370f5748.png)

![image](https://user-images.githubusercontent.com/79560566/131648865-1d69f8b7-6c55-4902-8440-6f3620aac696.png)

**Comment by Sophie-zh** [comment]
why... 最新版还是这样吗？（虽然旧版也没见过这情况

**Comment by Sophie-zh** [comment]
我想想咋办...

**Comment by YWolfeee** [comment]
@Little-Stream 看看好了吗

**Comment by Little-Stream** [comment]
我这里现在还没有欸（不知道是不是跟浏览器有关系，我的是edge）
