### ISSUE TITLE
天气的div里换行在不同浏览器下不同

### ISSUE THREAD

**Issue by Sophie-zh** [Yuanpei-Intelligence/YPPF#237]
<img width="381" alt="截屏2021-09-02 17 24 18" src="https://user-images.githubusercontent.com/55350524/131819468-0e476b62-bd44-4474-92bf-afde86272e03.png">

<img width="395" alt="截屏2021-09-02 17 24 23" src="https://user-images.githubusercontent.com/55350524/131819475-54d23a4e-0740-445f-a10a-9a145765d768.png">

**Comment by YWolfeee** [comment]
你这个是访问的服务器还是你的local呀

**Comment by pkuGenuine** [comment]
服务器上并没有问题吧
