### ISSUE TITLE
views.py中注册scheduler任务引起许多bug

### ISSUE THREAD

**Issue by XuRuihan** [Yuanpei-Intelligence/YPPF#242]
```python
register_events(scheduler)
scheduler.start()
```

1. `register_events(scheduler)`存在时，无法实现从空数据库makemigrations和migrate，报错信息为
    table yppf.django_scheduler.django_job not exist
2. `register_events(scheduler)`存在时，第一次runserver没有问题，多次runserver会报错，报错信息为
    job conflicts
总之肯定不能直接写在这里

**Comment by panhongtao07** [comment]
愚蠢的django-apscheduler在0.4版本废弃了register_events,0.5版本废弃了register_job，只要使用就会报错
