### ISSUE TITLE
上传照片为空时缺少提示

### ISSUE THREAD

**Issue by Little-Stream** [Yuanpei-Intelligence/YPPF#271]
![image](https://user-images.githubusercontent.com/79560566/132152768-9dbcc5c5-977c-4cb9-98c9-ba92061279d2.png)
![image](https://user-images.githubusercontent.com/79560566/132152775-10c006b7-2e20-46fe-b9f3-781635d7d28e.png)

**Comment by Sophie-zh** [comment]
收到
