### ISSUE TITLE
预报备活动老师拒绝后活动取消，但显示审核通过

### ISSUE THREAD

**Issue by Little-Stream** [Yuanpei-Intelligence/YPPF#277]
![image](https://user-images.githubusercontent.com/79560566/132186063-a545258c-feed-41b8-8cea-d8f805baad25.png)
![image](https://user-images.githubusercontent.com/79560566/132186065-2d7a7dbc-4f45-40a4-a241-be3f73454804.png)

**Comment by Little-Stream** [comment]
一开始的状态是“预报备+审核中”

**Comment by Little-Stream** [comment]
![image](https://user-images.githubusercontent.com/79560566/132186689-fa47ab4d-e899-490e-a47e-63cf6ea1556f.png)
![image](https://user-images.githubusercontent.com/79560566/132186692-ee19cf97-ca1c-410c-87c8-f1fbc6489bcf.png)
非预报备活动显示正常

**Comment by pkuGenuine** [comment]
我已经改掉了，可以 close
