### ISSUE TITLE
组织通过成员退出申请时出现bug

### ISSUE THREAD

**Issue by Little-Stream** [Yuanpei-Intelligence/YPPF#278]
![image](https://user-images.githubusercontent.com/79560566/132190253-541224fb-462a-4606-8856-511ee4a6ac0c.png)
![image](https://user-images.githubusercontent.com/79560566/132190260-0f6cdf24-9d05-4cba-b617-891f9236afb1.png)

**Comment by YWolfeee** [comment]
搞定了
更新完看下
