### ISSUE TITLE
在utils.py中导入utils_dependency时出错

### ISSUE THREAD

**Issue by Aubrey-Lu** [Yuanpei-Intelligence/YPPF#351]
报错信息：
from app.scheduler_func import changeActivityStatus, notifyActivity
**ImportError:** cannot import name 'changeActivityStatus' from partially initialized module 'app.scheduler_func' (most likely due to a circular import)
（develop分支）怀疑存在循环导入的情况。

**Comment by linhaowei1** [comment]
@panhongtao07 https://github.com/Yuanpei-Intelligence/YPPF/blob/develop/app/scheduler_func.py#:~:text=from%20app.activity_utils%20import%20calcu_activity_bonus

**Comment by linhaowei1** [comment]
@panhongtao07 
这句import使得scheduler_func.py 依赖app.activity_utils。https://github.com/Yuanpei-Intelligence/YPPF/blob/develop/app/scheduler_func.py#:~:text=from%20app.activity_utils%20import%20calcu_activity_bonus。而原本的app.activity_utils依赖scheduler_func.py。
有没有办法把这个计算活动bonus的逻辑放在别的地方？scheduler_func最好不要依赖于各种utils功能库？

**Comment by linhaowei1** [comment]
@Aubrey-Lu Hello学弟，如果你想先把项目跑起来，可以先把这句import删掉（https://github.com/Yuanpei-Intelligence/YPPF/blob/develop/app/scheduler_func.py#:~:text=from%20app.activity_utils%20import%20calcu_activity_bonus），如果不触发相关逻辑，部分代码应该还可以跑。

**Comment by linhaowei1** [comment]
已经修改了。
