### ISSUE TITLE
在makemigrations遇到的问题

### ISSUE THREAD

**Issue by SouthwestWindQ** [Yuanpei-Intelligence/YPPF#353]
我在cd进YPPF文件夹后，在命令行中执行python manage.py makemigrations，结果发现了如图所示的报错。
![4281642585941_ pic](https://user-images.githubusercontent.com/95567950/150106745-be41eb69-1e60-4022-ab6b-5080bbdbc751.jpg)
这个报错信息在网上查找不到解决方案，请各位学长学姐给予指点。不胜感激！

**Comment by qingzhenduyu** [comment]
注释掉对应的行即可
