### ISSUE TITLE
单次课程活动开设时，参数检查没有给用户具体的错误原因

### ISSUE THREAD

**Issue by Aubrey-Lu** [Yuanpei-Intelligence/YPPF#424]
https://github.com/Yuanpei-Intelligence/YPPF/blob/41f57d6e9763fbfaf9f40bbac21d54ab9749961a/app/course_views.py#L137-L147

经过测试，一旦用户填写不合法，系统都会自动回到首页，并且未告知具体原因，这样体验很不好。建议在填写页面提示用户原因，让用户重新填写。

**Comment by cqkmxpr** [comment]
收到，我改一下

**Comment by YWolfeee** [comment]
这个解决了吗 @cqkmxpr

**Comment by cqkmxpr** [comment]
pr#443在解决这个，学长提到的几个问题我再改一下 @YWolfeee

**Comment by panhongtao07** [comment]
已经初步解决
