### ISSUE TITLE
在进行开设课程的参数检查时，出现没有考虑到的问题

### ISSUE THREAD

**Issue by Aubrey-Lu** [Yuanpei-Intelligence/YPPF#426]
https://github.com/Yuanpei-Intelligence/YPPF/blob/41f57d6e9763fbfaf9f40bbac21d54ab9749961a/app/course_utils.py#L719-L729

当没有选择课程类型时，前端传回的值是空字符串，无法转换成int类型，而且外部没有做好错误处理，导致系统会直接报错。

**Comment by Aubrey-Lu** [comment]
@qingzhenduyu

**Comment by qingzhenduyu** [comment]
收到，下个PR会修复该bug
