### ISSUE TITLE
“发起选课页面”测试时发现的一些bug（更新中）

### ISSUE THREAD

**Issue by mavisguan** [Yuanpei-Intelligence/YPPF#427]
1.用户初次登陆修改密码之前，登录welcome页面（被迫读用户须知的时候）页面左侧的navbar显示的内容似乎不对，比如显示了“发起活动”但没显示“我的课程”？（不知道是不是只有我一个人是这样的）
2.用户填了不合法的课程信息，提交失败之后，系统把之前填写的其他正确信息也清空了：
<img width="960" alt="bug1" src="https://user-images.githubusercontent.com/58137527/154229923-2d2d55c0-fed9-40f2-b37f-40c9611ed898.png">

**Comment by mavisguan** [comment]
3.这个课程类别button的样式需要改改，把左边的圆角去掉...暂时没找到怎么改T T @Sophie-zh 请求援助
![U7VX1L4eLz](https://user-images.githubusercontent.com/58137527/154233096-7ae1c853-5512-4124-8e80-3e4d1f4a4e72.png)

**Comment by EchoShao8899** [comment]
> 1.用户初次登陆修改密码之前，登录welcome页面（被迫读用户须知的时候）页面左侧的navbar显示的内容似乎不对，比如显示了“发起活动”但没显示“我的课程”？（不知道是不是只有我一个人是这样的）

请问你是在课程小组还是普通小组？“我的课程”只对课程小组显示，其他小组显示“发起活动”“活动结项”。

**Comment by EchoShao8899** [comment]
> 3.这个课程类别button的样式需要改改，把左边的圆角去掉...暂时没找到怎么改T T @Sophie-zh 请求援助 ![U7VX1L4eLz](https://user-images.githubusercontent.com/58137527/154233096-7ae1c853-5512-4124-8e80-3e4d1f4a4e72.png) 以及在下拉菜单中选择一个选项之后，button上的文字会发生错位 ![image](https://user-images.githubusercontent.com/58137527/154262198-cb7d92eb-422f-4433-a476-86b40a4c3fcf.png)

是否统一成圆角按钮更好呢？

**Comment by YWolfeee** [comment]
这个解决完了吗

**Comment by mavisguan** [comment]
> 这个解决完了吗

（刚看到）前几天syj帮忙解决完了~
