### ISSUE TITLE
导入时报错

### ISSUE THREAD

**Issue by Aubrey-Lu** [Yuanpei-Intelligence/YPPF#433]
https://github.com/Yuanpei-Intelligence/YPPF/blob/313993c579c6e5bb6560250059896a0b0a76cc47/boottest/settings.py#L20

报错信息：
ImportError: cannot import name 'base_get_setting' from partially initialized module 'boottest' (most likely due to a circular import)

**Comment by YWolfeee** [comment]
正在紧急处理
