### ISSUE TITLE
反馈页面前端显示问题

### ISSUE THREAD

**Issue by Aubrey-Lu** [Yuanpei-Intelligence/YPPF#499]
<img width="738" alt="截屏2022-02-23 下午3 00 20" src="https://user-images.githubusercontent.com/72335144/155274184-7246cdb6-54e8-4c59-a878-11de6a2d6798.png">

撤回的地方多了一个框 @linhaowei1

**Comment by linhaowei1** [comment]
噫，我这边没有
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/56622542/155274903-632038a4-cf1b-4116-8cc8-7f68d01ca547.png">

**Comment by linhaowei1** [comment]
是不是不同浏览器的行为不一样啊..

**Comment by Aubrey-Lu** [comment]
我是safari

**Comment by Aubrey-Lu** [comment]
我用其他浏览器也是这样，试了Chrome和Firefox

**Comment by linhaowei1** [comment]
挺神奇的，我的浏览器都挺正常的..在研发中心群里问问有没有人能解决下叭
