### ISSUE TITLE
活动主页展示非在职状态成员

### ISSUE THREAD

**Issue by XuRuihan** [Yuanpei-Intelligence/YPPF#51]
/orginfo 活动主页展示了非在职状态成员，例如只是提交加入申请的成员。如图，提交多次申请的成员还会展示多次
![image](https://user-images.githubusercontent.com/50470253/127771067-08843410-8aca-43e7-b368-5db1d97afe89.png)

**Comment by YWolfeee** [comment]
提交申请的问题应该是人事变动解决，多提交的问题我觉得应该加一个判断就是人员变动的时候检测`(org,person)` pair是不是唯一，也是人事的
