### ISSUE TITLE
【组织管理】中【信息与隐私】的下标错误

### ISSUE THREAD

**Issue by XuRuihan** [Yuanpei-Intelligence/YPPF#52]
使用组织账户登录，点击【组织管理】-->【信息与隐私】，出现下列问题
![image](https://user-images.githubusercontent.com/50470253/127771999-74336fd3-6311-421c-a665-fc4d527f3d65.png)
![image](https://user-images.githubusercontent.com/50470253/127772011-10784c21-d804-419d-9c59-e73a90e10e4e.png)

**Comment by YWolfeee** [comment]
是的还没有改 这个应该是 @mrlazy1708 本周的事情
