### ISSUE TITLE
小组标签被遮挡

### ISSUE THREAD

**Issue by jyliu02** [Yuanpei-Intelligence/YPPF#549]
<img width="237" alt="截屏2022-03-13 上午10 15 34" src="https://user-images.githubusercontent.com/72335144/158041976-22e9a863-6cdd-48b2-880a-6bafece3a134.png">

如图，小组标签在被“触发”时会被上方元素遮挡。

**Comment by pkuGenuine** [comment]
Solved by [PR851](https://github.com/Yuanpei-Intelligence/YPPF/pull/851)
