### ISSUE TITLE
个人提交活动报名报错

### ISSUE THREAD

**Issue by Sophie-zh** [Yuanpei-Intelligence/YPPF#61]
尝试提交报名会出bug，调试发现是applyActivity函数里【可以读取willingness意愿点但会抛出异常】，没有测出具体是哪句...

**Comment by pkuGenuine** [comment]
能不能给一个错误样本？

**Comment by YWolfeee** [comment]
> 能不能给一个错误样本？

@Sophie-zh

**Comment by pkuGenuine** [comment]
前端的问题，应该是你改的时候把 input 里面的 aid 删了，我在改
