### ISSUE TITLE
书院课程“德智体美劳”分类识别消失

### ISSUE THREAD

**Issue by muyun727** [Yuanpei-Intelligence/YPPF#627]
在测试环境的【个人主页-我的活动】界面查看书院课程学时的时候，所有之前上过的课程的“课程类型”都变成了未分类
![b3677bdb9150fbf7f8f8fe039a42160](https://user-images.githubusercontent.com/112060494/186595435-da22dd54-4615-434f-a8fa-31052dd98492.jpg)

**Comment by pkuGenuine** [comment]
应该是测试数据库缺失信息导致，不是问题
