### ISSUE TITLE
元气值发放界面提示不足

### ISSUE THREAD

**Issue by panhongtao07** [Yuanpei-Intelligence/YPPF#78]
各个参数的意义，格式完全没有写明白，比如开始时间竟然是一个text，我怎么知道你接受哪种格式的时间作为输入？
而且失败了也没有任何提示，我都不知道哪里错了，只是简单返回到呈现所有实例的地方。
![1629092080(1)](https://user-images.githubusercontent.com/59553164/129515818-64785ad1-27b7-461a-89fd-8cf37843dd2e.png)

**Comment by panhongtao07** [comment]
后台都看不到报错信息，我真不知道咋填

**Comment by YWolfeee** [comment]
目前打算采用shell发放
