### ISSUE TITLE
个人主页的昵称和班级公开设置无效

### ISSUE THREAD

**Issue by panhongtao07** [Yuanpei-Intelligence/YPPF#84]
昵称总是不公开，班级总是公开

**Comment by YWolfeee** [comment]
昵称删掉，班级总是公开，个人的主页可能还需要调整

**Comment by panhongtao07** [comment]
连年级都可以不公开，班级也许不用公开吧，而且如果不能调整的话也许去掉选项或者设成disabled比较好

**Comment by YWolfeee** [comment]
不可以不公开。年级和班级现在保持公开。
可以直接删掉这两个的用户自选操作

**Comment by panhongtao07** [comment]
那就拒绝修改吧，年级要不也干脆不允许字段修改好了，而非仅是不能修改呈现状态
