### ISSUE TITLE
学生阅览组织主页侧边栏的内容不合理

### ISSUE THREAD

**Issue by panhongtao07** [Yuanpei-Intelligence/YPPF#85]
“组织活动”以及“组织管理”下属的在职成员和人事变动对非组织成员都是无效项，不应该呈现
![1629095346(1)](https://user-images.githubusercontent.com/59553164/129520469-240cc82c-5711-4026-8d4a-efe9d96c9686.png)

**Comment by YWolfeee** [comment]
这个栏要统一改，你直接加一个任务叫做siderbar修改吧
