### ISSUE TITLE
左边栏修改

### ISSUE THREAD

**Issue by YWolfeee** [Yuanpei-Intelligence/YPPF#97]
我已经把左边栏的统一化实现了，现在需要找一些logo把折叠的内容释放出来，没必要折叠了（当然修改信息那两个还是折叠）

**Comment by XuRuihan** [comment]
我做了几个logo，但是有几个太丑了不好看

**Comment by YWolfeee** [comment]
这个不是svg可以直接找来用吗@XuRuihan @Sophie-zh

**Comment by XuRuihan** [comment]
可以，但是我没找到统一风格的。
另一个关键的问题是，我在左边栏加了两个“我的活动”和“我的组织”，但是跳转后collapse没法自动展开

**Comment by YWolfeee** [comment]
可能需要统一一下logo
