### ISSUE TITLE
无“我的成员”的入口

### ISSUE THREAD

**Issue by qingzhenduyu** [Yuanpei-Intelligence/YPPF#99]
找不到“我的成员”的入口，如果是在人事管理的侧边栏的话，目前人事管理的侧边栏是展示不出来的

**Comment by YWolfeee** [comment]
我的成员应该是在组织主页呈现吧？应该已经有了啊，就是组织简介那儿的另一个navbar。
如果看完了确认没问题可以close

**Comment by qingzhenduyu** [comment]
> 我的成员应该是在组织主页呈现吧？应该已经有了啊，就是组织简介那儿的另一个navbar。
> 如果看完了确认没问题可以close

确实没找到orz
